# fly.toml file generated for bandwagonmon on 2022-10-11T17:24:39+08:00

app = "bandwagonmon"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  strategy = "immediate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
